### ISSUE TITLE
Can´t add a GEMItem to more than one GEMPage? 

### ISSUE THREAD

**Issue by manuelgonzalvez** [Spirik/GEM#50]
Hi, im' working on a rather big menu (as for today, about 90 GEMPages, 450 GEMItems), & having issues with ESP32 memory for other tasks. some of that items are references to the same object in struct, but execute different methods ( hence they go on different pages) . if I bind a GEMItem to certain page, i cannot bind it to a different one afterwards. 

any hints about this? is it a known limitation? thanks!

**Comment by Spirik** [comment]
Hi, Manuel! Wow, that's a really big menu you have there=)

Unfortunately, indeed, there is a limitation caused by inner [implementation](https://github.com/Spirik/GEM/blob/master/src/GEMPage.cpp#L46): Menu Item can not be nested inside multiple Menu Pages at the same time. This is due to the fact that GEMItem stores internally a pointer to the parent GEMPage and a pointer to the next GEMItem on that page, thus forming a linked list of menu items. So it can not be a part of a multiple linked lists at the same time.

**Comment by manuelgonzalvez** [comment]
Thanks!
